dist: focal

git:
  submodules: false

script:
  - sudo cp bin/zola-cn /usr/local/bin/zola && sudo chmod a+x /usr/local/bin/zola

# If you are using a different folder than `public` for the output directory, you will
# need to change the `zola` command and the `ghp-import` path
after_success: |
  [ $TRAVIS_BRANCH = code ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  zola build &&
  sudo pip install ghp-import &&
  ghp-import -c blog.gaxxx.me -n public -b master &&
  git push -fq https://${GH_TOKEN}@github.com/gaxxx/gaxxx.github.io.git master
