language: minimal
dist: bionic

git:
  submodules: false

before_script:
  # Download and unzip the zola executable
  # Replace the version numbers in the URL by the version you want to use
  - git clone https://github.com/jameshclrk/zola-slim themes/slim
  - curl -s -L https://github.com/getzola/zola/releases/download/v0.11.0/zola-v0.11.0-x86_64-unknown-linux-gnu.tar.gz | sudo tar xvzf - -C /usr/local/bin

script:
  - zola build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: public
  on:
    branch: master
